name: A workflow for my hello world file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Execute action a
       uses: ./action-a
       with:
        MY_NAME: "Layonn"
